### ISSUE TITLE
useful features with source code

### ISSUE THREAD

**Issue by Shikopat** [exteraSquad/exteraGram#10]
Ability to seek voice messages from player alert:
https://github.com/Forkgram/TelegramAndroid/commit/1c4b3e18d59e2a7c82fcc1f6b8224ece27e8e39b

feat: copy bot button
https://github.com/qwq233/Nullgram/commit/8e199778733a33636e0f58611c88c400852922cc

feat: add dismiss bottom in AppLinkVerify
https://github.com/qwq233/Nullgram/commit/2d94c10b26b5eaa17b0d25e3d5bdd7aaecc7c7df

feat: auto highlight code:
https://github.com/qwq233/Nullgram/commit/d9c2ad6c05f91115a2f86b65433f91676270c5bc

feat: preview hex color :
https://github.com/qwq233/Nullgram/commit/e93c39f015471b199dbc4e2dce3a791b7ddae62f

feat: Repeat as copy
https://github.com/blxueya/GuGugramX/commit/bf0636846b2cb754a49064ed93ba10899df8b6d5

 feat: add Unread Badge On Back Button
https://github.com/qwq233/Nullgram/commit/ad5e5afeb75c95636d5e6081a685d0c6ee700abd

 text style hide-able:
https://github.com/NextAlone/Nagram/commit/7c445b766b2a8b6b4a4eae893066aed1a1e67593

 feat: add great or poor
https://github.com/NextAlone/Nagram/commit/7e5a7ec5bcad0ccb99bba7e4e6df5e7fbd35643b

feat: add invert reply
https://github.com/NextAlone/Nagram/commit/696a9fbf8ef01bfd5741ce8d31d925ae7324bcde

 feat: add ccache
https://github.com/NextAlone/Nagram/commit/e589b4c09c37d636fa9ed8f52b3376c731ff9290

 feat: show timestamp in seconds
https://github.com/NekoX-Dev/NekoX/commit/04e62a0c0a5c939148b4d28c8148e42bfa3a1970

feat: remember all clicked replies:
https://github.com/NekoX-Dev/NekoX/commit/3c8ea5d10b6bb8cd5cfea36c7c04d0db727ba320

feat: duration info in Shared Voices tab.
https://github.com/Forkgram/TelegramAndroid/commit/23bd95967a006e5948c8f0ea80261b801a6f50cc

 feat: setting to disable flip through photos by tapping on their edge.
https://github.com/Forkgram/TelegramAndroid/commit/8179cab130a9dfba30f3ced4b856e3dd74cc3fad

Anonymous Forward button to top action bar with new icon.
https://github.com/Forkgram/TelegramAndroid/commit/efe3f7c04ef702301d27ce1ca2cb6a3ae0d58355

- Fixed wrong anonymous forwarding of messages with replies.
https://github.com/Forkgram/TelegramAndroid/commit/9a4a541ee8a68bc6e58d45738b7305c26a472b2a

feat: Anonymous Forward and Non-text Forward buttons to Share Alert.
https://github.com/Forkgram/TelegramAndroid/commit/8acf5e8296f3274b05253701a478b6db8c335982

Replaced Anonymous Forward in context menu with Fast Forward button.
https://github.com/Forkgram/TelegramAndroid/commit/f766ba12a9bdb09be69f01e02b47779094640d0d

feat: settings to replace original Forward with Fast Forward.
https://github.com/Forkgram/TelegramAndroid/commit/9ff9641b837033448b6bfff514ad6d152fec19a5

feat: ability to fast forward albums and group any items to albums.
https://github.com/Forkgram/TelegramAndroid/commit/4a577f528b7cf54c8685177bd66291feb6dc074c

feat: ability to silent fast forward with long click in share alert.
https://github.com/Forkgram/TelegramAndroid/commit/c454dad885bb0ff2a5d90aae9925d5e12c8ecfc7

feat: ability to fast forward media from webpage.
https://github.com/Forkgram/TelegramAndroid/commit/0a12a1f8b65f24a3dcd7d0a85eae4b9fc25d3d5a

feat: add dismiss bottom in App Link Verify
https://github.com/qwq233/Nullgram/commit/2d94c10b26b5eaa17b0d25e3d5bdd7aaecc7c7df

Added ability to attach text to voice message before sending it
https://github.com/Forkgram/TelegramAndroid/commit/2c4aee06b727fc4371e7ee7a125d88d68ced8b45

Add days of week to schedule time picker.
https://github.com/Forkgram/TelegramAndroid/commit/b28d68b6b4446b415aff438cec62f643e33bcc68

Add ability to reset item angle in Paint View
https://github.com/Forkgram/TelegramAndroid/commit/ac252d917d688dd90148eaba0204cf18e77ecb3c

Add ability to hide bottom button
https://github.com/Forkgram/TelegramAndroid/commit/120848425ee68daf5391df3a0c090447fbb6aeaa

Add auto inserting caption to cloud GIF if EditField has text.
https://github.com/Forkgram/TelegramAndroid/commit/18c603fe5ed4d24c3882dc41e7f876170e3d337a

Add option to disable sending sticker info in photos
https://github.com/Forkgram/TelegramAndroid/commit/a4319f55774893cc9190fb9f175c8ce597d9919d

Add Color Picker button in Photo Editor.
https://github.com/Forkgram/TelegramAndroid/commit/3244fd6cadc78c3826adb8f0194282b5e7bde091
`Attorelle: already`

feat: add undo/redo
https://github.com/NextAlone/Nagram/commit/6212558ee39453dac011cb906962f3a3eb74e5da

Raised forward/delete limits to 1024:
https://github.com/NextAlone/Nagram/commit/f2b7959490c7e79ec6651fce56726fa367bccc53
forward work natively while delete is not. Thats why delete have a "slicer" for a list with the ids.
For folks who ask: "WTF your map value contain list of the lists" well, key can be zero (0), but it in theory can contain the ids (here they check `if (newTaskId != 0)`) so to avoid rewriting values in this map we just add new chunks with ids.
If they will restrict native forward in future i will add same slicer too. Limit 1024 just to have it. It can be upto 2 billions, but after your client need to send all these chunks (=requests) and you can get api bans (for 5-10min due use abuse their api).
So, when you wanna forward 800 messages OR delete them think that TG servers control your API rates for certain api calls.

feat: support disable passcode unlock system ui
https://github.com/NextAlone/Nagram/commit/6802fb525cb3bf4f17881a4ead0789f6fe9e7f11

**Comment by Attorelle** [comment]
Thanks for the offer. We'll take a look at it.
