### ISSUE TITLE
Paid help: throwing dice

### ISSUE THREAD

**Issue by zhaocaijinbao1314** [exteraSquad/exteraGram#11]
The result of the user (not the robot) throwing the dice on telegram can be preset in advance?

**Comment by Attorelle** [comment]
@zhaocaijinbao1314 You can get the result of the roll in advance, but not set it

**Comment by zhaocaijinbao1314** [comment]
How long in advance can I know the result?  Please let me know, I am willing to pay

**Comment by Attorelle** [comment]
I've reopened this issue to answer you. I think the bots can't specify the dice roll result we want, which means we can't force the result we want.

**Comment by zhaocaijinbao1314** [comment]
> I've reopened this issue to answer you. I think the bots can't specify the dice roll result we want, which means we can't force the result we want.

We don't need to force the outcome, it's okay if we can predict the outcome

**Comment by Attorelle** [comment]
> We don't need to force the outcome, it's okay if we can predict the outcome

The result can be predicted if you "speed up" the dice animation in some way

**Comment by Attorelle** [comment]
Umm.. did some experiments. "Userbot" can force dice result. :thinking:

**Comment by Playez** [comment]
@Attorelle где кот

**Comment by immat0x1** [comment]
@Attorelle кот где сука

**Comment by Playez** [comment]
@Playez жду кота

**Comment by clownless** [comment]
@Playez ты похож на кота хочу забрать тебя домой

**Comment by itsreallyv1eds** [comment]
@Playez кот блять где

**Comment by Playez** [comment]
@clownless не надо меня забирать

**Comment by Attorelle** [comment]
Stop spamming here.

**Comment by Playez** [comment]
@Attorelle сука кота отдавай

**Comment by itsreallyv1eds** [comment]
@Attorelle иди нахуй

**Comment by immat0x1** [comment]
@Attorelle слыш ты ебало то завали

**Comment by Playez** [comment]
@Playez так где кот то я не понял

**Comment by itsreallyv1eds** [comment]
@Playez кот сдох блять

**Comment by immat0x1** [comment]
@itsreallyv1eds христос воскрес

**Comment by Playez** [comment]
@immat0x1 поправляю виедса, воистину воскрес*
