### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by TeaqariaWTF** [exteraSquad/exteraGram#14]
add option to disable vibration when scrolling between channels like nekogramx

when translating in different languages ​​add translation in message instead of popup  ( nekogram , nekogramx , owlgram )

add option to disable badge counter

**Comment by immat0x1** [comment]
1. k
2. idk
3. k

**Comment by Playez** [comment]
@immat0x1 Во первых, не нервируйся, подростковая любовь шняга интересная, дальше же, поговори с ней об игре, да да, именно игре, либо играх, но если деваха сидит в тик токах - она сидит много с подружками, если же ты застенчив, значит это будет тебя сильно пульсировать, после уроков поговори на тему игр, там, девчонки чаще всего играют в геншин импакт, разные хорроры любят, будь просто юморной чел, если за мемасики нормальные шаришь и не паришь - красавчик, деваха в твоих руках. Если ей не нравятся игры - поговори о смешных ситуациях, сначало делай это с небольшой улыбкой, потом дня два - смейся до упада. Если ты тотально хочешь с ней войти в контакт, тогда тебе стоит шутить прикольно, с тоном таким, главное чувак не шлёпать по жопе, с девушками надо как с пацанами, почти одно и то же, просто чуть мягче, так они тоже в игры играют, пшикайся духами, юзай дезик и главное имей голову чистую, девочки не любят, когда голова жир говяный. Вот и все впринципе, девочки любят решительных, смешных. И насчёт пошлятины и вэйпа - сам свидетель того, как мне девочка говорила, что тот одноклассник неадекват. Вообщем вывод : смешно шути, топ гигиена, и да, не стоит ее сразу приглашать в гости, лучше на третий день
