### ISSUE TITLE
Never ending loading circle ..

### ISSUE THREAD

**Issue by Cris--** [exteraSquad/exteraGram#15]
On some media i get a never ending loading circle and can't save these to gallery with v8.8.3. With v8.7.4 it works!

A12  AOSP, no Ad-Blocker.

**Comment by Playez** [comment]
@Cris-- хахтих момент

**Comment by clownless** [comment]
@Playez

**Comment by Cris--** [comment]
Fixed in v8.8.5!

**Comment by Playez** [comment]
@Cris-- хахтих момент короче
