### ISSUE TITLE
Not centered header on homepage, when centering option enabled

### ISSUE THREAD

**Issue by xmdnx** [exteraSquad/exteraGram#18]
wtf 💀💀

enable "Center headers" option is Extera Settings

go to homepage
![IMG_20221016_024218_911](https://user-images.githubusercontent.com/72883689/196011983-ad35ab72-2277-48b5-b504-69bf99428299.jpg)

**Comment by Playez** [comment]
@xmdnx go sleep bro

**Comment by xmdnx** [comment]
> @xmdnx go sleep bro

no 🥵

**Comment by xmdnx** [comment]
miss clicked

**Comment by xmdnx** [comment]
fixed in beta

**Comment by immat0x1** [comment]
*redebalo*

**Comment by xmdnx** [comment]
токси, в бете пофикшено?

**Comment by itsv1eds** [comment]
@xmdnx да
