### ISSUE TITLE
Stop playing music while listening to a voice message

### ISSUE THREAD

**Issue by igorechek06** [exteraSquad/exteraGram#19]
**Is your feature request related to a problem? Please describe.**
Every time I want to listen to a voice message I have to stop my music. It is very uncomfortable.

**Describe the solution you'd like**
Add option in settings 🤯

**P.S**
Music played from another app.

**Comment by Playez** [comment]
@igorechek06 щлуш

**Comment by bulatorr** [comment]
immat0x1 верни крестик, заебал

**Comment by Playez** [comment]
> immat0x1 верни крестик, заебал

после обеда

**Comment by immat0x1** [comment]
ДОЛБОЕБОВ КРЕСТИК

**Comment by bulatorr** [comment]
ну сделай переключатель отключения крестика хули

**Comment by bulatorr** [comment]
как можно делать лучший клиент телеги на данный момент, и вырезать такую полезную функцию. заебалось голосовые по 5 минут в конец перематывать

**Comment by Playez** [comment]
> ну сделай переключатель отключения крестика хули



> как можно делать лучший клиент телеги на данный момент, и вырезать такую полезную функцию. заебалось голосовые по 5 минут в конец перематывать

а ты их попробуй в меню музыки переключить

**Comment by bulatorr** [comment]
> можно ты свайп вверх научишься делать

это неудобно, может из винды ещё крестик вырезать и по иконке программы два раз тыкать, как в Windows 1.01?

**Comment by Playez** [comment]
> > можно ты свайп вверх научишься делать
> 
> это неудобно, может из винды ещё крестик вырезать и по иконке программы два раз тыкать, как в Windows 1.01?

да

**Comment by immat0x1** [comment]
> > можно ты свайп вверх научишься делать
> 
> это неудобно, может из винды ещё крестик вырезать и по иконке программы два раз тыкать, как в Windows 1.01?

подкинь идею разрабам мб добавят

**Comment by bulatorr** [comment]
> подкинь идею разрабам мб добавят

они в восьмёрке так делали, говна поели. неужели сложно вернуть функцию, которая там была?

**Comment by Playez** [comment]
@bulatorr согласен блин обратись в разрабам винды охуели совсем

**Comment by immat0x1** [comment]
> > подкинь идею разрабам мб добавят
> 
> они в восьмёрке так делали, говна поели. неужели сложно вернуть функцию, которая там была?

хз трудно или нет, спроси у них, я был бы рад если бы вернули
