### ISSUE TITLE
Feature Matrial YOU 

### ISSUE THREAD

**Issue by MrTokyo12345** [exteraSquad/exteraGram#2]
It would be very nice to have the colors of the material you also on telegram

**Comment by Attorelle** [comment]
@MrTokyo12345 чего

**Comment by itsreallyv1eds** [comment]
> It would be very nice to have the colors of the material you also on telegram 

already have

**Comment by Playez** [comment]
христос воскрес

**Comment by immat0x1** [comment]
@Playez воистину воскрес

**Comment by xmdnx** [comment]
Хуйню сотворили, а не Material You
