### ISSUE TITLE
[Feature Request] Set a Reminder in Message menu

### ISSUE THREAD

**Issue by PiRomant** [exteraSquad/exteraGram#20]
Combination of Save message and Schedule Message.
Open Schedule dialog to set a reminder to Saved message by tapping Message menu button.
![image (2)](https://user-images.githubusercontent.com/29551044/199711326-62ccdb05-b979-40e1-ab55-e924f54967e9.png)

**Comment by xmdnx** [comment]
Нахуя?

**Comment by immat0x1** [comment]
useless.
