### ISSUE TITLE
Always show downloads button 

### ISSUE THREAD

**Issue by mohamedamrnady** [exteraSquad/exteraGram#22]
**Is your feature request related to a problem? Please describe.**
I just need to recall an old file

**Describe the solution you'd like**
Adding a toggle to always show it 

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by xmdnx** [comment]
uhhhhhhhhhmmm

**Comment by immat0x1** [comment]
will be added in a drawer.
