### ISSUE TITLE
Broken package 

### ISSUE THREAD

**Issue by stafe-box** [exteraSquad/exteraGram#23]
Realese package is cant install on samsung phone
Show's package is broker
![Screenshot_20230203_163823_Package installer](https://user-images.githubusercontent.com/81144919/216594602-95b3a5b9-eeae-4d5a-a0e0-d9600fb0fece.jpg)

**Comment by Playez** [comment]
@stafe-box are you installing or updating the app? if updating, there's a chance that before, you installed a specific(non-universal) version, and that's why you can't update

**Comment by stafe-box** [comment]
@Playez, thanks, I deleted app and instaled from apk
