### ISSUE TITLE
[Feature Request] Please add it on IzzyOnDroid or F-droid

### ISSUE THREAD

**Issue by git-Hmmm** [exteraSquad/exteraGram#25]
**Is your feature request related to a problem? Please describe.**
Yes, I always have to manually install updates. It would be beneficial to have exteraGram available in IzzyOnDroid or the F-Droid Official Repository, as this would make installation and updates easier.

**Describe the solution you'd like**
- If possible, please adjust this app to meet the [F-Droid inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy) and list it on the official F-Droid Repo.
- If not possible, we always have [IzzyOnDroid](https://gitlab.com/IzzyOnDroid/repo#how-can-i-get-my-favorite-app-listed-there)

**Describe alternatives you've considered**
I am using [Nekogram X from F-Droid](https://f-droid.org/en/packages/nekox.messenger/) for now.

**Additional context**
none

**Comment by playez** [comment]
@git-Hmmm if we would want to go on fdroid, we would need to make the app foss itself, and that's what we don't want to do.

**Comment by playez** [comment]
@git-Hmmm we've made a foss version back to 8.2.7... but then, nobody used it, so it was removed

**Comment by git-Hmmm** [comment]
@playez OK Sure, How about IzzyOnDroid Repo?

**Comment by playez** [comment]
> @playez OK Sure, How about IzzyOnDroid Repo?

does izzyondroid allow non-foss apps?

**Comment by git-Hmmm** [comment]
![IMG_20230215_215729_833](https://user-images.githubusercontent.com/102938585/219090171-655a7a9d-c72e-4522-878d-a6b06dbe1b42.jpg)
Yes they allow proprietary dependencies.

**Comment by git-Hmmm** [comment]
@playez 
![IMG_20230215_215729_833](https://user-images.githubusercontent.com/102938585/219090171-655a7a9d-c72e-4522-878d-a6b06dbe1b42.jpg)
Yes they allow proprietary dependencies.

Read more [here](https://gitlab.com/IzzyOnDroid/repo#what-are-the-requirements-an-app-must-meet-to-be-included-with-the-repo)

**Comment by xmdnx** [comment]
btw already avaliable on RuStore.
