### ISSUE TITLE
[Feature request] add material icons 

### ISSUE THREAD

**Issue by T8RIN** [exteraSquad/exteraGram#29]
Can you add material design icons to the settings, so i can use "solar", default, or "md icons" from this site for example "https://pictogrammers.com"

Why? Because this mod is really beautiful and brings us MDY theming to the telegram app, but material icons will make it way more cooler for some people, who is crazy about this 

Thanks for the attention ❤️

**Comment by Suburbanno** [comment]
+1

**Comment by Guanran928** [comment]
Cherrygram also provides "VKUI" icons, which is what we don't have in exteraGram, this should be implemented in exteraGram as well.
![Screenshot](https://github.com/exteraSquad/exteraGram/assets/68757440/47943aba-fc1c-43c9-8b72-4d69e66c35b2)

**Comment by immat0x1** [comment]
not all icons fit the telegram interface:
• vkui icons are too bold and take up too much space
• I don’t like Google icons at all, they are all in a different style

make a pull request, I'll take a look at it, but I don't want to do it myself.
