### ISSUE TITLE
[Feature Request] Ability to Save Stickers to Gallery

### ISSUE THREAD

**Issue by errorgurumeditation** [exteraSquad/exteraGram#41]
**Is your feature request related to a problem? Please describe.**
not really

**Describe the solution you'd like**
It would be pretty great to have a menu option to save a sticker to my device's gallery

**Describe alternatives you've considered**
Closest thing i could think of would be some sort of Telegram bot, but that would be outside the scope of exteraGram

**Additional context**
The feature currently exists in [Nekogram X](https://github.com/NekoX-Dev/NekoX)

**Comment by immat0x1** [comment]
will be available in next update
