### ISSUE TITLE
[Feature Request] Divide "Force Snow" into multiple sub-options

### ISSUE THREAD

**Issue by Guanran928** [exteraSquad/exteraGram#43]
**Is your feature request related to a problem? Please describe.**
Cherrygram have this neat feature, where you can enable snow effect on specific elements - which is missing on exteraGram.

**Describe the solution you'd like**
Implement "Force Snow" as 3 sub-options, similar to Cherrygram.
![Screenshot](https://github.com/exteraSquad/exteraGram/assets/68757440/12dd99ce-76c8-4ad0-972d-4612c54f3d2b)

**Comment by immat0x1** [comment]
how often will it be used? rarely.

this function makes no sense

**Comment by Guanran928** [comment]
> how often will it be used? rarely.
> 
> this function makes no sense

Well, personally I'd prefer adding snow to the title bar - but not the chat background.
It is just a personal preference, and I wish there will be more customization options in exteraGram, to fit more peoples' personal preference.
