### ISSUE TITLE
App crashes in dialogs

### ISSUE THREAD

**Issue by FLALLIKA** [exteraSquad/exteraGram#49]
**Describe the bug**
App is crashing

**To Reproduce**
Idk, how to reproduce this, bcs, it works very strange. I just scroll up the chat with videomessages from me and other people, nd it crashed. After restarting, app crashes too, when i open this chat. 

**Expected behavior**
I expected, that the will not crash

**Screenshots**
I have the log 
This is link in pastebin
https://pastebin.com/JQG5b8Ty
Password is HelloWorld1

**Smartphone (please complete the following information):**
 - Device: Realme 9 Pro 5G
 - OS: Android 13, Realme UI 4.0
 - Version 10.1. 1

**Additional context**

**Comment by playez** [comment]
>Version 10.1. 1
updat before reporting??

**Comment by FLALLIKA** [comment]
> > Version 10.1. 1
> 
> updat before reporting??

At the time of the report, the latest version was installed, now this problem is no longer observed.

**Comment by playez** [comment]
> > > Version 10.1. 1
> > 
> > 
> > updat before reporting??
> 
> At the time of the report, the latest version was installed, now this problem is no longer observed.

why no close issue?? waste time ？？？？

**Comment by FLALLIKA** [comment]
> > > > Version 10.1. 1
> > > 
> > > 
> > > updat before reporting??
> > 
> > 
> > At the time of the report, the latest version was installed, now this problem is no longer observed.
> 
> why no close issue?? waste time ？？？？

Bcz i forgot about this issue
