### ISSUE TITLE
no install on samsing s2 

### ISSUE THREAD

**Issue by user2549028451451** [exteraSquad/exteraGram#5]
no work say bad pakag

**Comment by Playez** [comment]
@user2549028451451

**Comment by Playez** [comment]
@Playez да ебучий бот почему он на стикеры реагирует

**Comment by itsreallyv1eds** [comment]
@user2549028451451

**Comment by Attorelle** [comment]
@user2549028451451 Supported Android 5.x Lollipop to 13 Tiramisu

**Comment by user2549028451451** [comment]
what is loillop

**Comment by Attorelle** [comment]
We don't support versions of Android below 5.0 (Lollipop). You can install custom ROM to use exteraGram.
