### ISSUE TITLE
update source code

### ISSUE THREAD

**Issue by gmankab** [exteraSquad/exteraGram#54]
hey, update sources pls

**Comment by itsv1eds** [comment]
@gmankab https://t.me/exteraFAQ/25

**Comment by gmankab** [comment]
you are in beta for six months?

**Comment by itsv1eds** [comment]
@gmankab Yes. 
Check t.me/exteraGram and t.me/exteraGramCI

**Comment by gmankab** [comment]
release is here, update sources please
