### ISSUE TITLE
broken readme

### ISSUE THREAD

**Issue by xmdnx** [exteraSquad/exteraGram#68]
https://ibb.co/5FZmWcS

divider at top crosses logo

**Comment by itsv1eds** [comment]
your browser bug

**Comment by xmdnx** [comment]
@itsv1eds no, it's not browser bug. it's bottom divider of exteraGram title
`## exteraGram`

**Comment by Suburbanno** [comment]
This solves it here https://github.com/exteraSquad/exteraGram/pull/36
@itsv1eds @playez @xmdnx 

![image](https://github.com/exteraSquad/exteraGram/assets/13632826/94177640-29d7-4977-b98a-469fa8c3c157)

i have this bug too

![image](https://github.com/exteraSquad/exteraGram/assets/13632826/febac13f-7080-41cf-a335-f3564dc75d4c)
