### ISSUE TITLE
Some useful commits for exteraGram (wih source code)

### ISSUE THREAD

**Issue by Shikopat** [exteraSquad/exteraGram#7]
Ability to seek voice messages from player alert:
https://github.com/Forkgram/TelegramAndroid/commit/1c4b3e18d59e2a7c82fcc1f6b8224ece27e8e39b

Days of week to schedule time picker.
https://github.com/Forkgram/TelegramAndroid/commit/8f42f0c1b75794920d56e4ae353478cc9e9eb8f0
`Attorelle: added`

Duration info in Shared Voices tab:
https://github.com/Forkgram/TelegramAndroid/commit/ec79dfe6161d301613628a2b1cc59773a0064f9e
`Attorelle: added`

Raised forward/delete limits to 1024:
https://github.com/NextAlone/Nagram/commit/f2b7959490c7e79ec6651fce56726fa367bccc53

**Comment by Attorelle** [comment]
@Shikopat Лимиты не трогать

**Comment by Gherkashen2** [comment]
Add Disable Greeting Sticker:
https://github.com/qwq233/Nullgram/commit/ec5444d83bf91d66d28ecd67a2eaa7a2ef227373

Add Disable Jump To Next Channel:
https://github.com/qwq233/Nullgram/commit/74ea61967cee186f4ace048eb127a934e93729a5

**Comment by Gherkashen2** [comment]
Removed white background for recording of round video messages:
https://github.com/Forkgram/TelegramAndroid/commit/2bcf7718f20ebc636036474ec4e5a7efe6338a56

Ability to delete all your messages in group:
https://github.com/Forkgram/TelegramAndroid/commit/90c282768c4f81bff05f55d4b6df7aeae05df831

Ability to select all messages between 2 selections from bar:
https://github.com/Forkgram/TelegramAndroid/commit/52fc8eec1e4f51d92b04c082572b6d9f363cd9a5

Add settings to replace original Forward with Fast Forward:
https://github.com/Forkgram/TelegramAndroid/commit/0f36337d73c6c5053971751da1e30ecd2dee3ab8

**Comment by Attorelle** [comment]
Something was added. Thanks! <3

**Comment by immat0x1** [comment]
@Attorelle я негр
