### ISSUE TITLE
All chat folder unaccessible/missing

### ISSUE THREAD

**Issue by Legend4iry** [exteraSquad/exteraGram#71]
All chat folder is missing or unaccessible

Exteragram app:
![Screenshot_20240423_143640](https://github.com/exteraSquad/exteraGram/assets/167849220/9e9efc51-c38f-44c5-92ef-54e41f82048a)

Telegram app:
![Screenshot_20240423_143628](https://github.com/exteraSquad/exteraGram/assets/167849220/9554498b-6aaf-4578-ba4e-de18fb2e2dfc)

And also the "people nearby" option is also missing from Exteragram

Exteragram app:
![Screenshot_20240423_144211](https://github.com/exteraSquad/exteraGram/assets/167849220/57187ad6-79d4-48aa-97ce-69895ce1b475)

Telegram app:
![Screenshot_20240423_144131](https://github.com/exteraSquad/exteraGram/assets/167849220/fc49b74b-5e2d-4bda-bbb6-a7c8353786d9)

**Comment by ZavaruKitsu** [comment]
> All chat folder is missing or unaccessible

exteraGram Preferences -> Appearance -> Hide "All Chats" Tab

> And also the "people nearby" option is also missing from Exteragram

exteraGram Preferences -> Appearance -> Drawer Elements
